### ISSUE TITLE
Preparations for conda package

### ISSUE THREAD

**Issue by tovrstra** [fire-carrot/wildcard#1]
I'd like to package this for conda-forge: https://conda-forge.org/
It would be nice for the purpose of packaging to make a few small changes:

- a file LICENSE.txt with the license.
- `setup.py` says the license is GPL, but not which version.
- In 'setup.py` the option `zip_safe=False` could interfere with packaging and does not seem to be needed here. (very minor issue)

@agalera Do you accept pull requests for such changes?

**Comment by agalera** [comment]
Hello!

Of course, pull requests are accepted, I had planned to use GPL 3.0.
You can go making the changes if you wish, in a few hours I can add the license :+1:

**Comment by tovrstra** [comment]
No worries. I'll take care. It would be nice if you could review as I'm also including a few minor things before I'd like to package it.
